-- CREACION DE FUNCIONES

-- CONCATENA NOMBRE + NUMERO DE CONTACTO

DELIMITER //

CREATE FUNCTION CONTACTO_A_LLAMAR (idClie INT)
RETURNS VARCHAR(100)
READS SQL DATA
BEGIN
DECLARE RESULTADO VARCHAR(100);

IF idClie <= 0 THEN
SET RESULTADO = "El numero debe ser mayor a 0";
ELSE
SELECT CONCAT (Nombre, ' ',Telefono)
INTO RESULTADO
FROM Cliente

 WHERE idCliente = idClie;
END IF;
RETURN RESULTADO;
END//


DELIMITER ;
-- PRUEBA
select CONTACTO_A_LLAMAR(1140621793);

-- BUSCAR NOMBRE CATEGORIA

DELIMITER //

CREATE FUNCTION BUSCAR_CATEGORIA (idCate INT)
RETURNS VARCHAR(100)
READS SQL DATA
BEGIN
DECLARE Nombre VARCHAR(100);
Set Nombre = (select NombreCategoria from categoria where idCategoria = idCate); 
RETURN Nombre;
END//


DELIMITER ;

-- PRUEBA
select BUSCAR_CATEGORIA(2);
select BUSCAR_CATEGORIA(3);

-- PRUEBA
select NombreProducto, idCategoria, BUSCAR_CATEGORIA(idCategoria) from Producto;